mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
#  type-aliases-package: com.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${mysql.user}
    password: ${mysql.password}
    url: ${mysql.url}
